M48
; DRILL file {KiCad 9.0.6} date 2026-03-07T16:21:18-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-07T16:21:18-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X253.87Y-46.99
X253.87Y-52.77
T2
X55.9Y-25.35
X55.9Y-142.1
X255.15Y-25.35
X255.15Y-142.1
M30
